'use strict';
const titles=['The Quiet Death of Productivity Theater','Why We Moved Our Blockchain to a Spreadsheet','On Building Slowly — and Shipping Fast','The Future Is Not a Feature. It\'s a Feeling.','Hot Take: Buttons Should Be Invisible','Accessibility Theater — and What Comes After','How We Scaled to Three Users','Our New Logo Cost $4M. Here\'s Why It Was Worth It.','Dark Mode Is a Mindset','Mobile Users Aren\'t Real — A Manifesto','Lorem Ipsum — A Retrospective','We Replaced QA With Vibes'];
const subjects=[
  'Busy dashboards do not always mean useful work. Start with a clear outcome, give the team time to focus, and measure what actually changes for the people using the product.',
  'A familiar spreadsheet can make a small process easier to understand. Choose a tool for the work it needs to do, keep a clear record of changes, and move to something larger when the problem demands it.',
  'Building slowly means paying attention to the decisions that are expensive to reverse. Small, testable releases let a team learn quickly without losing that care.',
  'A useful product answers a specific need. Good feedback, clear language, and predictable behavior help people understand what happened and what they can do next.',
  'A button needs to look and behave like a button. Give it a descriptive label, a visible focus state, and enough room to operate on a touch screen.',
  'Accessibility is part of everyday product work. Try the experience with a keyboard, check text contrast, label inputs, and listen to what a screen reader announces.',
  'Even a product with three users benefits from dependable behavior. Watch those people complete their actual tasks before choosing the next feature.',
  'A logo is only one part of a product identity. Consistent language, typography, and interaction patterns usually affect the everyday experience much more.',
  'Dark mode should make the interface easier to read in a different environment. Both themes need readable text, recognizable controls, and charts that keep their meaning.',
  'People use real products on small screens. Test the content at a narrow width, make navigation reachable, and let the layout adapt without shrinking the whole page.',
  'Placeholder copy helps test layout, but real words reveal different problems. Replace it before release and check long titles, empty states, and messages that explain an error.',
  'Good intentions do not verify a calculation. Use known answers, test boundary cases, and exercise the full journey through the same controls a person will use.'
];
const POSTS=Array.from({length:60},(_,i)=>({id:i,title:titles[i%12]+(i>11?` (Part ${Math.floor(i/12)+1})`:''),cat:['AI','Blockchain','Life','AI'][i%4],date:1704067200000+i*86400000*9,likes:24+(i*17)%180,img:`assets/journal-${i%6}.jpg`,body:[subjects[i%12],'For our team, the practical starting point is one small change we can verify. We write down the expected result, test it with realistic inputs, and keep the next step clear.','This journal is a collection of demo essays about that approach. Take the idea that fits your work, try it on a small scale, and share what you learn with the community.']}));
let liked=Core.read('likedPosts',[]);if(!Array.isArray(liked))liked=[];liked=new Set(liked.filter(n=>Number.isInteger(n)&&n>=0&&n<60));
let page=1,list=POSTS;const PER=6;const expanded=new Set();const esc=Core.escape;
function draw(){
  const pages=Math.max(1,Math.ceil(list.length/PER));page=Math.max(1,Math.min(page,pages));const offset=(page-1)*PER;
  document.getElementById('posts').innerHTML=list.length?list.slice(offset,offset+PER).map(post=>`<article class="post ${expanded.has(post.id)?'open':''}" id="post-${post.id}"><div class="img"><img src="${post.img}" alt="" width="640" height="400" loading="lazy" decoding="async"></div><div class="post-copy"><div class="num">Essay ${post.id+1}</div><div class="cat">${post.cat}</div><h2>${esc(post.title)}</h2><div class="meta"><time datetime="${new Date(post.date).toISOString()}">${Core.date(post.date)}</time> · 2 min read</div><div class="body" id="body-${post.id}" ${expanded.has(post.id)?'':'hidden'}>${post.body.map(p=>`<p>${esc(p)}</p>`).join('')}</div><div class="actions"><button class="secondary" type="button" data-read="${post.id}" aria-expanded="${expanded.has(post.id)}" aria-controls="body-${post.id}">${expanded.has(post.id)?'Close essay':'Read essay'}</button><button class="secondary like" type="button" data-like="${post.id}" aria-pressed="${liked.has(post.id)}" aria-label="${liked.has(post.id)?'Unlike':'Like'} ${esc(post.title)}">${liked.has(post.id)?'♥':'♡'} ${post.likes+(liked.has(post.id)?1:0)}</button></div></div></article>`).join(''):'<p class="empty">No articles match. Try another search or choose all topics.</p>';
  document.getElementById('pno').textContent=list.length?`Page ${page} of ${pages}`:'No results';document.getElementById('blog-result').textContent=`${list.length} ${list.length===1?'essay':'essays'}${document.getElementById('q').value.trim()?' matching your search':''}`;document.getElementById('blog-prev').disabled=page<=1;document.getElementById('blog-next').disabled=page>=pages;
}
function search(){const q=document.getElementById('q').value.trim().toLowerCase(),cat=document.getElementById('cat').value;list=POSTS.filter(p=>p.title.toLowerCase().includes(q)&&(cat==='all'||p.cat===cat));page=1;draw();}
document.getElementById('blog-search').addEventListener('submit',e=>{e.preventDefault();search();});document.getElementById('q').addEventListener('input',search);document.getElementById('cat').addEventListener('change',search);
document.getElementById('blog-prev').addEventListener('click',()=>{page--;draw();document.getElementById('posts').scrollIntoView();});document.getElementById('blog-next').addEventListener('click',()=>{page++;draw();document.getElementById('posts').scrollIntoView();});
document.getElementById('posts').addEventListener('click',e=>{
  const read=e.target.closest('[data-read]'),like=e.target.closest('[data-like]');
  if(read){const id=Number(read.dataset.read);expanded.has(id)?expanded.delete(id):expanded.add(id);draw();document.querySelector(`[data-read="${id}"]`)?.focus();}
  if(like){const id=Number(like.dataset.like),next=new Set(liked);next.has(id)?next.delete(id):next.add(id);if(!Core.save('likedPosts',[...next])){toast('Could not save your like.');return;}liked=next;draw();document.querySelector(`[data-like="${id}"]`)?.focus();}
});
const featured=document.createElement('dialog');featured.id='featured-dialog';featured.setAttribute('aria-labelledby','featured-title');featured.innerHTML='<button type="button" class="secondary dialog-close" aria-label="Close essay">×</button><span class="eyebrow">Featured essay</span><h2 id="featured-title">Craft is not dead. It\'s evolving.</h2><p>Care shows up in the choices that help someone finish a task: a label that makes sense, a calculation that gives the right answer, a layout that works on the device in their hand.</p><p>Tools can help us work faster. They cannot replace deciding what the product should do or checking that it does it. We keep that responsibility close to the people building and using the product.</p><p>For this demo journal, craft means simple interactions, accessible controls, and honest feedback. That is work we can improve every day.</p>';document.body.appendChild(featured);document.getElementById('featured-read').addEventListener('click',()=>featured.showModal());featured.querySelector('button').addEventListener('click',()=>featured.close());
function progress(){const height=document.documentElement.scrollHeight-window.innerHeight;document.getElementById('reading').style.width=`${height>0?Math.min(100,window.scrollY/height*100):0}%`;}
window.addEventListener('scroll',progress,{passive:true});window.addEventListener('resize',progress);draw();progress();
