const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const Tools = require('../js/tools.js');
const Core = require('../js/globals.js');
const Orders = require('../js/admin.js');
let passed = 0;
function test(name, fn) { fn(); console.log('PASS', name); passed++; }
test('KM uses exact international mile', () => assert.equal(Tools.miles('1.609344'), 1));
test('KM empty and negative are rejected', () => {assert.throws(()=>Tools.miles(''));assert.throws(()=>Tools.miles('-1'));});
test('BMI converts centimeters to meters', () => {const r=Tools.bmi('70','175');assert.equal(r.value.toFixed(1),'22.9');assert.equal(r.category,'healthy weight');});
test('BMI category boundaries', () => {assert.equal(Tools.bmi(18.5,100).category,'healthy weight');assert.equal(Tools.bmi(25,100).category,'overweight');assert.equal(Tools.bmi(30,100).category,'obesity');});
test('BMI rejects zero height', () => assert.throws(()=>Tools.bmi(70,0)));
test('Bill arithmetic remains numeric', () => {const r=Tools.split('100','10','2');assert.equal(r.total,11000);assert.equal(r.each,5500);});
test('Bill splitting distributes remaining cents', () => {const r=Tools.split('10','0','3');assert.equal(r.lower*r.count+r.extra,r.total);assert.equal(r.lower,333);assert.equal(r.extra,1);});
test('Bill rejects zero and fractional party size', () => {assert.throws(()=>Tools.split(100,10,0));assert.throws(()=>Tools.split(100,10,1.5));});
test('Currency uses editable target rate', () => assert.equal(Tools.currency('100','.9'),90));
test('Currency rejects invalid and zero rates', () => {assert.throws(()=>Tools.currency(100,0));assert.throws(()=>Tools.currency(100,'USD → BTC'));});
test('Password length and all character groups', () => {for(const length of [12,16,64,128]){const p=Tools.password(length);assert.equal(p.length,length);for(const re of [/[a-z]/,/[A-Z]/,/\d/,/[!@#$%^&*()\-_=+]/])assert.match(p,re);}});
test('Passwords are not fixed outputs', () => assert.notEqual(Tools.password(16),Tools.password(16)));
test('Password bounds', () => {assert.throws(()=>Tools.password(8));assert.throws(()=>Tools.password(129));});
test('Age before and after birthday', () => {assert.equal(Tools.age('2000-09-28',new Date(2026,8,27)),25);assert.equal(Tools.age('2000-09-27',new Date(2026,8,27)),26);});
test('Age validates impossible and future dates', () => {assert.throws(()=>Tools.age('2025-02-29'));assert.throws(()=>Tools.age('9999-01-01'));assert.throws(()=>Tools.age('01/02/2000'));});
test('Contrast black/white is 21:1', () => assert.equal(Tools.contrast('#000000','#ffffff'),21));
test('Contrast equal colors is 1:1', () => assert.equal(Tools.contrast('#eee','#eeeeee'),1));
test('Contrast order is symmetric', () => assert.equal(Tools.contrast('#123456','#abcdef'),Tools.contrast('#abcdef','#123456')));
test('Contrast rejects malformed colors', () => assert.throws(()=>Tools.contrast('#nothex','#fff')));
test('HTML escaping does not execute markup', () => assert.equal(Core.escape('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;'));
test('CSV quotes delimiters and protects formulas', () => {assert.equal(Core.csv([['a,b','"quoted"','=1+1']]),'"a,b","""quoted""","\'=1+1"');});
test('Valid modern email patterns', () => {assert.equal(Core.email('first.last+test@example.io'),true);assert.equal(Core.email('bad email'),false);});
const context={window:{}};vm.createContext(context);vm.runInContext(fs.readFileSync(require.resolve('../js/data.js'),'utf8'),context);const rows=context.window.ORDERS;
test('Dataset totals retain all 2,000 records and cents', () => {const r=Orders.summary(rows);assert.equal(r.count,2000);assert.equal(r.cents,99675955);assert.equal(r.qty,9925);});
test('Numeric amounts sort numerically', () => assert.deepEqual(Orders.filter([{id:'1',customer:'a',email:'a',product:'a',status:'paid',date:1,cents:200},{id:'2',customer:'b',email:'b',product:'b',status:'paid',date:1,cents:1000}], '', 'all', 'amount-asc').map(o=>o.cents),[200,1000]));
test('Case-insensitive customer and ID search', () => {assert.ok(Orders.filter(rows,'OLGA').length);assert.equal(Orders.filter(rows,'ord-100000').length,1);});
test('Unknown status filters accurately', () => assert.ok(Orders.filter(rows,'','unknown').every(o=>o.status==='unknown')));
test('Empty order summaries remain finite', () => assert.equal(Orders.summary([]).average,0));
test('Light theme body text contrast',()=>assert.ok(Tools.contrast('#182334','#f6f8fc')>=4.5));
test('Dark theme muted text contrast',()=>assert.ok(Tools.contrast('#a3a9b7','#141821')>=4.5));
console.log(`${passed} regression checks passed.`);
