const fs=require('node:fs');const assert=require('node:assert/strict');const {chromium}=require('playwright-core');
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{const context=await browser.newContext();const page=await context.newPage();const errors=[],failed=[],remote=[];page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>{if(r.url().startsWith('http://localhost:4174'))failed.push(r.url())});page.on('response',r=>{if(r.status()>=400&&r.url().startsWith('http://localhost:4174'))failed.push(r.status()+' '+r.url());});page.on('request',r=>{if(!r.url().startsWith('http://localhost:4174')&&!r.url().startsWith('data:'))remote.push(r.url());});
for(const width of [1440,360,768]){await page.setViewportSize({width,height:900});await page.goto('http://localhost:4174/',{waitUntil:'domcontentloaded'});await page.waitForTimeout(700);assert.ok((await page.title()).includes('Nexora'));assert.ok(await page.locator('h1').count());assert.equal(await page.locator('main').count(),1);assert.ok(await page.locator('a[href="admin.html"]').count());assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.screenshot({path:'output/clone-home-'+width+'.png'});}
await page.getByText('Menu',{exact:true}).first().click();
const destination=page.locator('nav.menu .nexora-portal').getByRole('link',{name:'Dashboard',exact:true});
await destination.waitFor({state:'visible'});await page.screenshot({path:'output/clone-menu.png'});await destination.click();await page.waitForURL('**/admin.html');assert.equal(await page.locator('#cnt').textContent(),'2,000');
await page.setViewportSize({width:1440,height:900});await page.goto('http://localhost:4174/admin.html');assert.equal(await page.locator('#cnt').textContent(),'2,000');assert.equal(await page.locator('#rev').textContent(),'$996,759.55');await page.getByLabel('Search orders').fill('ORD-100000');assert.equal(await page.locator('#orders tbody tr').count(),1);await page.getByLabel('Search orders').fill('');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'output/clone-dashboard.png',fullPage:true});
fs.writeFileSync('output/clone-results.json',JSON.stringify({errors,failed,remote},null,2));console.log({errors,failed,remoteVideoRequests:remote.length});assert.equal(errors.length,0);assert.equal(failed.length,0);
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
